steps:
  - name: gradle:6.7-jdk11
    entrypoint: gradle
    args: ["test"]
  - name: gradle:6.7-jdk11
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/guitar-shack", "--build-arg=JAR_FILE=build/libs/guitar-shack-1.0-SNAPSHOT.jar", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/guitar-shack' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ '-c', 'run', 'deploy', 'guitar-shack', '--image', 'gcr.io/$PROJECT_ID/guitar-shack', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated' ]
    secretEnv: ['ACCOUNT_SID', 'AUTH_TOKEN', 'FROM_PHONE_NUMBER', 'TO_PHONE_NUMBER']
images: ["gcr.io/$PROJECT_ID/guitar-shack"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ACCOUNT_SID/versions/1
      env: 'ACCOUNT_SID'
    - versionName: projects/$PROJECT_ID/secrets/AUTH_TOKEN/versions/1
      env: 'AUTH_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/FROM_PHONE_NUMBER/versions/1
      env: 'FROM_PHONE_NUMBER'
    - versionName: projects/$PROJECT_ID/secrets/TO_PHONE_NUMBER/versions/1
      env: 'TO_PHONE_NUMBER'
