steps:
  - name: gradle:5.6.2-jdk11
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.6.2-jdk11
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/guitar-shack", "--build-arg=JAR_FILE=build/libs/guitar-shack-1.0-SNAPSHOT.jar", "."]
images: ["gcr.io/$PROJECT_ID/guitar-shack"]
